package view.staffView;

import view.customerView.*;
import dao.StaffDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Staff;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class DefaultStaffView extends javax.swing.JPanel {

    private static Staff staffSelect;
    private ArrayList<Staff> list;
    private StaffDAO sd = new StaffDAO();
    

    //null contructor
    public DefaultStaffView(int num) {

    }

    public DefaultStaffView() {
        initComponents();
        StaffDAO sd = new StaffDAO();
        list = sd.selectAll();
        setTableStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(staffTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void setTableStaff() {
        DefaultTableModel dtm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        staffTable.setModel(dtm);
        ListSelectionModel lsm = staffTable.getSelectionModel();
        lsm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsm.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                crearteStaff();
            }
        });
        setColumnName(dtm);
        setColumnWidths(staffTable, 100, 400, 100, 100, 100, 200, 400, 100, 100);
        setRow(dtm);
    }

    private void setColumnName(DefaultTableModel dtm) {
        dtm.addColumn("Mã nhân viên");
        dtm.addColumn("Tên nhân viên");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Tên Chức Vụ");
        dtm.addColumn("Số Điện Thoại");
        dtm.addColumn("Địa Chỉ");
//        dtm.addColumn("Mã Lương");
//        dtm.addColumn("Mã Tài Khoản");
    }

    public void setColumnWidths(JTable table, int... widths) {
        TableColumnModel columnModel = table.getColumnModel();
        for (int i = 0; i < widths.length; i++) {
            if (i < columnModel.getColumnCount()) {
                columnModel.getColumn(i).setMaxWidth(widths[i]);
            } else {
                break;
            }
        }
    }

    public void setRow(DefaultTableModel dfm) {
        Vector v = null;
        for (Staff s : list) {
            v = new Vector();
            
            v.removeAllElements();
            v.add(s.getMaNhanVien());
            v.add(s.getTenNhanVien());
            v.add(s.getNgaySinh());
            v.add(s.getGioiTinh());    
            v.add(s.getChucVu());
            v.add(s.getSdt());
            v.add(s.getDiaChi());
            dfm.addRow(v);

        }

    }

    public void crearteStaff() {
        int row = staffTable.getSelectedRow();
        int maNhanVien = (Integer) staffTable.getValueAt(row, 0);
        staffSelect = new Staff();
        staffSelect.setMaNhanVien(maNhanVien);
    }

    public static Staff getStaffSelected() {
        return staffSelect;
    }
    
    public static void setNullSelect() {
        staffSelect = null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable staffTable;
    // End of variables declaration//GEN-END:variables
}
