/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.staffView;

import controller.StaffService;
import controller.UserService;
import dao.StaffDAO;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import model.Payroll;
import model.Staff;
import util.Validate;

/**
 *
 * @author Trinh
 */
public class FixStaffView extends javax.swing.JPanel {

    private Staff staffFix;
    private StaffService ss = new StaffService();

    public FixStaffView() {
        initComponents();

        Staff staff = DefaultStaffView.getStaffSelected();
        staffFix = ss.findID(staff.getMaNhanVien());
        staffName.setText(staffFix.getTenNhanVien());
        staffAddress.setText(staffFix.getDiaChi());
        staffPhone.setText(staffFix.getSdt());
        staffYear.setDate(staffFix.getNgaySinh());
        staffPosition.setSelectedItem(staffFix.getChucVu());
        if (staffFix.getGioiTinh() == "Nam") {
            genderMale.setSelected(true);
        } else {
            genderFemale.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fixStaffBtn = new javax.swing.JButton();
        staffName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        staffAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        staffPhone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        staffPosition = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        genderMale = new javax.swing.JRadioButton();
        genderFemale = new javax.swing.JRadioButton();
        message = new javax.swing.JLabel();
        errorName = new javax.swing.JLabel();
        errorAdress = new javax.swing.JLabel();
        errorPhone = new javax.swing.JLabel();
        errorPosition = new javax.swing.JLabel();
        staffYear = new com.toedter.calendar.JDateChooser();
        errorGender = new javax.swing.JLabel();
        errorDOB = new javax.swing.JLabel();
        header = new javax.swing.JLabel();

        fixStaffBtn.setText("Sửa Thông Tin");
        fixStaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixStaffBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên Nhân Viên");

        staffAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffAddressActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày Sinh");

        jLabel3.setText("Giới Tính");

        staffPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPhoneActionPerformed(evt);
            }
        });

        jLabel27.setText("Chức Vụ");

        jLabel6.setText("Địa Chỉ");

        staffPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giám Đốc", "Kế Toán", "Lễ Tân", "Bảo Vệ" }));

        jLabel7.setText("Số Điện Thoại");

        genderMale.setText("Nam");

        genderFemale.setText("Nữ");
        genderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        message.setForeground(new java.awt.Color(13, 110, 253));

        header.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Sửa Nhân Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fixStaffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffName, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addComponent(staffAddress)
                    .addComponent(staffPhone)
                    .addComponent(staffPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffYear, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genderMale)
                                .addGap(35, 35, 35)
                                .addComponent(genderFemale)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(447, 447, 447)
                    .addComponent(errorDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(header)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(staffName)
                    .addComponent(jLabel3)
                    .addComponent(genderMale)
                    .addComponent(genderFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorGender, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(staffYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(fixStaffBtn)
                .addGap(155, 155, 155)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(errorDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fixStaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixStaffBtnActionPerformed
        boolean check;
        config();
        ArrayList<Integer> test1 = Validate.checkMutiLine("empty", staffName.getText(), staffAddress.getText(), staffPhone.getText(), (String) staffPosition.getSelectedItem());
        ArrayList<Integer> test2 = Validate.checkMutiLine("isNumber", staffPhone.getText());

        if ((!test1.isEmpty()) || (!genderMale.isSelected() && !genderFemale.isSelected())) {
            if (!genderMale.isSelected() && !genderFemale.isSelected()) {
                errorGender.setForeground(new Color(255, 0, 0));
                errorGender.setText("Vui Lòng Tích vào trường này");
            }
            callMessErrorEmpty(test1);
        }else if (genderFemale.isSelected() && genderMale.isSelected()) {
            errorGender.setForeground(new Color(255, 0, 0));
            errorGender.setText("Vui Lòng Tích 1 Lựa Chọn Duy Nhất");
        } 
        else if (!test2.isEmpty()) {
            callMessErrorNumber(test2);
        } else {
            String ten_nhan_vien = staffName.getText();
            java.util.Date nam_sinh = staffYear.getDate();
            String gender = "";
            if (genderMale.isSelected()) {
                gender += "Nam";
            } else {
                gender += "Nữ";
            }
            String dia_chi = staffAddress.getText();
            String so_dien_thoai = staffPhone.getText();
            String tenChucVu = (String) staffPosition.getSelectedItem();
            check = ss.update(new Staff(staffFix.getMaNhanVien(), ten_nhan_vien, nam_sinh, gender, tenChucVu, so_dien_thoai, dia_chi));
            if (check) {
                message.setForeground(new Color(13, 110, 253));
                message.setText("Sửa Nhân Viên Thành Công");
            } else {
                message.setForeground(new Color(255, 0, 0));
                message.setText("Sửa Nhân Viên Thất Bại");
            }
        }
    }//GEN-LAST:event_fixStaffBtnActionPerformed

    private void staffPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPhoneActionPerformed

    private void genderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleActionPerformed

    private void staffAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffAddressActionPerformed

    private void callMessErrorEmpty(ArrayList<Integer> idError) {
        for (Integer i : idError) {
            switch (i) {
                case 1:
                    errorName.setForeground(new Color(255, 0, 0));
                    errorName.setText("Vui lòng nhập trường này");
                    break;
                case 2:
                    errorAdress.setForeground(new Color(255, 0, 0));
                    errorAdress.setText("Vui lòng nhập trường này");
                    break;
                case 3:
                    errorPhone.setForeground(new Color(255, 0, 0));
                    errorPhone.setText("Vui lòng nhập trường này");
                    break;
                case 4:
                    errorPosition.setForeground(new Color(255, 0, 0));
                    errorPosition.setText("Vui lòng nhập trường này");
                    break;
                case 5:
                    errorDOB.setForeground(new Color(255, 0, 0));
                    errorDOB.setText("Vui lòng nhập trường này");
                    break;
                default:
                    break;
            }
        }
    }
    
    private void callMessErrorNumber(ArrayList<Integer> idError) {
        for (Integer i : idError) {
            switch (i) {
                case 1:
                    errorPhone.setForeground(new Color(255, 0, 0));
                    errorPhone.setText("Vui lòng chỉ nhập số");
                    break;
                case 2:
                    errorDOB.setForeground(new Color(255, 0, 0));
                    errorDOB.setText("Vui lòng chỉ nhập số");
                    break;
                default:
                    break;
            }
        }
    }

    private void config() {
        errorName.setText("");
        errorAdress.setText("");
        errorPhone.setText("");
        errorPosition.setText("");
        errorGender.setText("");
        errorDOB.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorAdress;
    private javax.swing.JLabel errorDOB;
    private javax.swing.JLabel errorGender;
    private javax.swing.JLabel errorName;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel errorPosition;
    private javax.swing.JButton fixStaffBtn;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JTextField staffAddress;
    private javax.swing.JTextField staffName;
    private javax.swing.JTextField staffPhone;
    private javax.swing.JComboBox<String> staffPosition;
    private com.toedter.calendar.JDateChooser staffYear;
    // End of variables declaration//GEN-END:variables

}
