/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.customerView;

import controller.CustomerService;
import controller.MenuController;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Customer;

/**
 *
 * @author Admin
 */
public class CustomerView extends javax.swing.JPanel {

    private MenuController controller;
    private CustomerService cs = new CustomerService();

    public CustomerView() {
        initComponents();
        controller = new MenuController(cusView);
        controller.setViewCustomer(new JButton());
        backBtn.setEnabled(Boolean.FALSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cusMenu = new javax.swing.JPanel();
        addCustomerBtn = new javax.swing.JButton();
        fixCusBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        delCusBtn1 = new javax.swing.JButton();
        cusView = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1110, 800));

        addCustomerBtn.setText("Thêm Khách Hàng");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        fixCusBtn.setText("Sửa Khách Hàng");
        fixCusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixCusBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Trở Lại");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        delCusBtn1.setText("Xoá Khách Hàng");
        delCusBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCusBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cusMenuLayout = new javax.swing.GroupLayout(cusMenu);
        cusMenu.setLayout(cusMenuLayout);
        cusMenuLayout.setHorizontalGroup(
            cusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(fixCusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(delCusBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        cusMenuLayout.setVerticalGroup(
            cusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(cusMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustomerBtn)
                    .addComponent(fixCusBtn)
                    .addComponent(backBtn)
                    .addComponent(delCusBtn1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cusViewLayout = new javax.swing.GroupLayout(cusView);
        cusView.setLayout(cusViewLayout);
        cusViewLayout.setHorizontalGroup(
            cusViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        cusViewLayout.setVerticalGroup(
            cusViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cusView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cusMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(cusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cusView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        fixCusBtn.setEnabled(Boolean.TRUE);
        delCusBtn1.setEnabled(Boolean.TRUE);
        backBtn.setEnabled(Boolean.FALSE);
        DefaultCustomerView.setNullSelect();
        controller.setViewCustomer(backBtn);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        fixCusBtn.setEnabled(Boolean.FALSE);
        delCusBtn1.setEnabled(Boolean.FALSE);
        backBtn.setEnabled(Boolean.TRUE);
        controller.setViewCustomer(addCustomerBtn);
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void fixCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixCusBtnActionPerformed

        Customer c = DefaultCustomerView.getCustomerSelected();
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Nhân Viên Cần Sửa Thông Tin", "Thông Báo", JOptionPane.ERROR_MESSAGE);
        } else {
            fixCusBtn.setEnabled(Boolean.FALSE);
            delCusBtn1.setEnabled(Boolean.FALSE);
            backBtn.setEnabled(Boolean.TRUE);
            controller.setViewCustomer(fixCusBtn);
        }
    }//GEN-LAST:event_fixCusBtnActionPerformed

    private void delCusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCusBtnActionPerformed

    }//GEN-LAST:event_delCusBtnActionPerformed

    private void delCusBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCusBtn1ActionPerformed
        Customer c = DefaultCustomerView.getCustomerSelected();
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Nhân Viên Cần Xoá", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int check = JOptionPane.showConfirmDialog(this, "Bạn có Chắc Muốn Xoá Khách Hàng này ? \n Việc xoá khách hàng có thể làm mất thông tin mãi mãi ", "Xác Nhận", JOptionPane.YES_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                boolean isDel = cs.delete(c);
                if (isDel) {
                    controller.setViewCustomer(new JButton());
                    JOptionPane.showMessageDialog(this, "Đã Xoá Thành Công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delCusBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel cusMenu;
    private javax.swing.JPanel cusView;
    private javax.swing.JButton delCusBtn1;
    private javax.swing.JButton fixCusBtn;
    // End of variables declaration//GEN-END:variables
}
