/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.billView;

import controller.ItemServiceService;
import dao.CustomerDAO;
import dao.RegisterFormDAO;
import java.awt.Component;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import model.Customer;
import model.RegistrationForm;
import model.Service;

/**
 *
 * @author Admin
 */
public class DetailBillView extends javax.swing.JPanel {

    private int cusSelect;
    private CustomerDAO cd = new CustomerDAO();
    private RegisterFormDAO reg = new RegisterFormDAO();
    private ItemServiceService iss = new ItemServiceService();

    public DetailBillView() {
        initComponents();
        DefaultTableModel dtm = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        detailTable.setModel(dtm);
        ListSelectionModel lsm = detailTable.getSelectionModel();
        lsm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setColumnName(dtm);
        setColumnWidths(detailTable, 400, 200, 100, 100, 200, 200);
        setRow(dtm);
        TableCellRenderer renderer = new CurrencyRenderer();
        detailTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        detailTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        DefaultBillView.setCus();
    }

    private void setColumnName(DefaultTableModel dtm) {
        dtm.addColumn("Tên Khách Hàng");
        dtm.addColumn("Tên Sản Phẩm");
        dtm.addColumn("Số Lượng");
        dtm.addColumn("Đơn Giá");
        dtm.addColumn("Loại");
        dtm.addColumn("Thành Tiền");
    }

    public void setColumnWidths(JTable table, int... widths) {
        TableColumnModel columnModel = table.getColumnModel();
        for (int i = 0; i < widths.length; i++) {
            if (i < columnModel.getColumnCount()) {
                columnModel.getColumn(i).setMaxWidth(widths[i]);
            } else {
                break;
            }
        }
    }

    public void setRow(DefaultTableModel dfm) {
        Vector v1 = new Vector();
        cusSelect = DefaultBillView.getCus();
        Customer c = cd.findById(cusSelect);
        RegistrationForm r = reg.findByIDCus(cusSelect);
        v1.add(c.getTenKhachHang());
        v1.add(c.getMaPhong().getName());
        v1.add((Integer) r.getThoiGianThue());
        v1.add(c.getKieuthue());
        v1.add(c.getMaPhong().getRoomType());
        v1.add(r.getTongTien());
        dfm.addRow(v1);
        Vector v2 = null;
        ArrayList<Service> list = iss.findByIdCus(cusSelect);
        double price = 0;
        for (Service s : list) {
            v2 = new Vector();
            v2.removeAllElements();
            v2.add("");
            v2.add(s.getNameItem());
            v2.add((Integer) s.getQuantity());
            v2.add(s.getPrice());
            v2.add("");
            v2.add(s.getTotalPay());
            price += s.getTotalPay();
            dfm.addRow(v2);
        }
        Vector v3 = new Vector();
        v3.add("");
        v3.add("");
        v3.add("");
        v3.add("");
        v3.add("");
        v3.add(r.getTongTien()+ price);
        dfm.addRow(v3);

    }
      static class CurrencyRenderer extends DefaultTableCellRenderer {
        private static final NumberFormat FORMAT = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof Double) {
                value = FORMAT.format(value);
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detailTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
